### ISSUE TITLE
翻译任务认领说明

### ISSUE THREAD

**Issue by elonehoo** [vitest-dev/docs-cn#51]
# 翻译任务认领说明

> 注意：
>
> 1. 一次尽量只认领一篇，给其他小伙伴留些机会~
> 2. 认领开始前，请务必阅读 [翻译流程说明](https://github.com/vitest-dev/docs-cn/issues/50)
> 3. 如果在翻译的时候发现有任何未同步的地方，及时指出，谢谢！

从 Todo List 中选取未被人领取过的文章：

未被领取过：

-  install

领取过：

-  install ([@elonehoo](https://github.com/elonehoo))

领取过，已完成：

-  install ([@elonehoo](https://github.com/elonehoo)) [docs (cn) : `api/toThrowErrorMatchingSnapshot` translation #49](https://github.com/vitest-dev/docs-cn/pull/49)

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  install | @elonehoo | 2022.05.06 - 2022.05.06
```

示例效果：

| Section | Title   | 译者                                     | 完成时间                |
| ------- | ------- | ---------------------------------------- | ----------------------- |
| guide   | install | [@elonehoo](https://github.com/elonehoo) | 2021.05.18 - 2021.05.20 |

当完成时，请修改自己的认领评论，添加 PR 信息：

| Section | Title   | 译者      | 完成时间                | PR |
| ------- | ------- | --------- | ----------------------- | --- |
| guide   | install | [@elonehoo](https://github.com/elonehoo) | 2021.05.18 - 2021.05.20 | [#49](https://github.com/vitest-dev/docs-cn/pull/49) |

## 任务认领列表

Todo List:

- [x] api
  - [x] toThrowErrorMatchingSnapshot ([@elonehoo](https://github.com/elonehoo)) [docs (cn) : `api/toThrowErrorMatchingSnapshot` translation #49](https://github.com/vitest-dev/docs-cn/pull/49)
  - [x] toThrowErrorMatchingInlineSnapshot ([@murongg](https://github.com/murongg)) [docs(cn): api/toThrowErrorMatchingInlineSnapshot translation](https://github.com/vitest-dev/docs-cn/pull/53)
  - [x] toSatisfy ([@murongg](https://github.com/murongg)) [docs(cn): api/toSatisfy translation #54](https://github.com/vitest-dev/docs-cn/pull/54)
  - [x] expect.addSnapshotSerializer ([@murongg](https://github.com/murongg)) [docs(cn): api/expect.addSnapshotSerializer translation #55](https://github.com/vitest-dev/docs-cn/pull/55)
  - [x] expect.extend ([@murongg](https://github.com/murongg)) [docs(cn): api/expect.extend translation #56](https://github.com/vitest-dev/docs-cn/pull/56)
  - [x] toMatchSnapshot ([@murongg](https://github.com/murongg)) [docs(cn): api/toMatchSnapshot translation #57](https://github.com/vitest-dev/docs-cn/pull/57)
  - [x] toMatchInlineSnapshot ([@murongg](https://github.com/murongg)) [docs(cn): api/toMatchInlineSnapshot translation #58](https://github.com/vitest-dev/docs-cn/pull/58)
- [x] config
  - [x] allowOnly ([@murongg](https://github.com/murongg)) [docs(cn): config/allowOnly translation #59](https://github.com/vitest-dev/docs-cn/pull/59)
  - [x] passWithNoTests ([@murongg](https://github.com/murongg)) [docs(cn): config/passWithNoTests translation #60](https://github.com/vitest-dev/docs-cn/pull/60)
- [x] guide
  - [x] extending-matchers.md ([@amadeus711](https://github.com/amadeus711)) [docs(guide): translate extending matchers #63](https://github.com/vitest-dev/docs-cn/pull/63)
  - [x] snapshot-serializer.md ([@murongg](https://github.com/murongg)) [docs(cn): guide/snapshot-serializer.md translation #61](https://github.com/vitest-dev/docs-cn/pull/61)
  - [x] 「migration.md/Vue Snapshots」([@watonyweng](https://github.com/watonyweng)) [docs(cn): translate Vue Snapshots in guide/migration.md #62](https://github.com/vitest-dev/docs-cn/pull/62)

**Comment by elonehoo** [comment]
| Section | Title   | 译者      | 完成时间                | PR |
| ------- | ------- | --------- | ----------------------- | --- |
| api   | toThrowErrorMatchingSnapshot | [@elonehoo](https://github.com/elonehoo) | 2021.05.18 - 2021.05.20 | [#49](https://github.com/vitest-dev/docs-cn/pull/49) |

**Comment by amadeus711** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  extending-matchers | @amadeus711  | 2022.05.18 - 2022.05.20

**Comment by murongg** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api |  toThrowErrorMatchingInlineSnapshot | @murongg | 2022.05.08 - 2022.05.08

**Comment by murongg** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api |  toSatisfy | @murongg | 2022.05.08

**Comment by murongg** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api |  expect.addSnapshotSerializer | [@murongg](https://github.com/murongg) | 2022.05.08

**Comment by murongg** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api |  expect.extend | [@murongg](https://github.com/murongg) | 2022.05.09

**Comment by murongg** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api |  toMatchSnapshot | @[murongg](https://github.com/murongg) | 2022.05.09

**Comment by murongg** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
api |  toMatchSnapshot | [@murongg](https://github.com/murongg) | 2022.05.09

**Comment by murongg** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
config |  allowOnly | [@murongg](https://github.com/murongg) | 2022.05.10 |

**Comment by murongg** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
config |  passWithNoTests | [@murongg](https://github.com/murongg) | 2022.05.10 |

**Comment by murongg** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | -- 
guide |   snapshot-serializer.md | [@murongg](https://github.com/murongg) | 2022.05.10

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| guide | migration/Vue Snapshots | @watonyweng | 2022.05.10 - 2022.05.12 | - |

**Comment by elonehoo** [comment]
感谢各位的帮助

**Comment by elonehoo** [comment]
@watonyweng 
@murongg 
@amadeus711 
> 排序随意

感谢各位的帮助，这次的同步文档翻译到此结束，

我们将会马不停蹄的开启下一次的同步翻译，十分感谢各位！

**Comment by elonehoo** [comment]
我这几天可能要去面试一下，然后找个房子，可能下次的issue是晚上发起的，不好意思啊

**Comment by murongg** [comment]
> 我这几天可能要去面试一下，然后找个房子，可能下次的issue是晚上发起的，不好意思啊

祝顺利

**Comment by watonyweng** [comment]
> 我这几天可能要去面试一下，然后找个房子，可能下次的issue是晚上发起的，不好意思啊

祝面试顺利，找到一份好工作。

**Comment by amadeus711** [comment]
> 我这几天可能要去面试一下，然后找个房子，可能下次的issue是晚上发起的，不好意思啊

要不要帮你内推蓝湖？

**Comment by elonehoo** [comment]
> > 我这几天可能要去面试一下，然后找个房子，可能下次的issue是晚上发起的，不好意思啊
> 
> 
> 
> 要不要帮你内推蓝湖？

我应该不配的。
