### ISSUE TITLE
翻译任务认领说明

### ISSUE THREAD

**Issue by elonehoo** [vitest-dev/docs-cn#66]
# 翻译任务认领说明

> 注意：
>
> 1. 一次尽量只认领一篇，给其他小伙伴留些机会~
> 2. 认领开始前，请务必阅读 [翻译流程说明](https://github.com/vitest-dev/docs-cn/issues/50)
> 3. 如果在翻译的时候发现有任何未同步的地方，及时指出，谢谢！

从 Todo List 中选取未被人领取过的文章：

未被领取过：

-  install

领取过：

-  install ([@elonehoo](https://github.com/elonehoo))

领取过，已完成：

-  install ([@elonehoo](https://github.com/elonehoo)) [docs (cn) : `api/toThrowErrorMatchingSnapshot` translation #49](https://github.com/vitest-dev/docs-cn/pull/49)

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  install | @elonehoo | 2022.05.06 - 2022.05.06
```

示例效果：

| Section | Title   | 译者                                     | 完成时间                |
| ------- | ------- | ---------------------------------------- | ----------------------- |
| guide   | install | [@elonehoo](https://github.com/elonehoo) | 2021.05.18 - 2021.05.20 |

当完成时，请修改自己的认领评论，添加 PR 信息：

| Section | Title   | 译者      | 完成时间                | PR |
| ------- | ------- | --------- | ----------------------- | --- |
| guide   | install | [@elonehoo](https://github.com/elonehoo) | 2021.05.18 - 2021.05.20 | [#49](https://github.com/vitest-dev/docs-cn/pull/49) |

## 任务认领列表

Todo List:

- [ ] guide
  - [x] index.md ([@elonehoo](https://github.com/elonehoo)) [docs(cn): getting started translation #69](https://github.com/vitest-dev/docs-cn/pull/69)
  - [x] coverage.md ([@elonehoo](https://github.com/elonehoo)) [docs(cn): coverage translation #70](https://github.com/vitest-dev/docs-cn/pull/70)
  - [ ] extending-matchers.md
  - [x] filtering.md (@amadeus711) [docs(guide): translate filtering #71](https://github.com/vitest-dev/docs-cn/pull/71)
  - [x] ui.md (@amadeus711) [docs(guide): translate vitest UI #73](https://github.com/vitest-dev/docs-cn/pull/73)

**Comment by elonehoo** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/index.md | 首页 | @elonehoo | 2022.06.11

**Comment by elonehoo** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/coverage.md |  coverage | @elonehoo | 2022.06.15 -

**Comment by elonehoo** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide/ extending-matchers.md |  extending-matchers | @elonehoo | 2022.06.15

**Comment by amadeus711** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
filtering.md | filtering | @amadeus711  | 2022.06.16 - 2022.06.18 | -

**Comment by justforuse** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  extending-matchers | @justforuse | 2022.06.27 | #74

**Comment by elonehoo** [comment]
谢谢各位，我们要跟官方文档进行同步啦
